id = "everforest"
name = "Everforest"
description = "A green based color scheme designed to be warm and soft in order to protect developers' eyes over long periods of work."
version = "0.1.0"
schema_version = 1
authors = ["Sainnhe Park <https://github.com/sainnhe>", "Kimberli Zhong <https://github.com/kimberli>"]
repository = "https://github.com/kimberli/everforest-zed"

[extension]
version = "0.1.0"
schema_version = 1

[[extension.themes]]
path = "themes/everforest-dark.json"

[[extension.themes]]
path = "themes/everforest-light.json"
